Scenario data downloaded from: https://live.magicc.org/scenarios

In [21]:
import pandas as pd
import xarray as xr
import numpy as np

import matplotlib.pyplot as plt
%matplotlib widget 
# ^ allows zooming in to the plots!

import cmocean as cm    

import gcsfs
fs = gcsfs.GCSFileSystem()

# loading csvs

In [22]:
temp119 = pd.read_csv('/home/jovyan/galen_course/SSP119_magicc_202408131930.csv')
temp126 = pd.read_csv('/home/jovyan/galen_course/SSP126_magicc_202408131930.csv')
temp245 = pd.read_csv('/home/jovyan/galen_course/SSP245_magicc_202408131930.csv')
temp370 = pd.read_csv('/home/jovyan/galen_course/SSP370_magicc_202408131929.csv')
temp434 = pd.read_csv('/home/jovyan/galen_course/SSP434-over_magicc_202408131929.csv')
temp585 = pd.read_csv('/home/jovyan/galen_course/SSP585_magicc_202408131252.csv')

## TEMPERATURES

In [23]:
### getting temperatures from dataframe ###

# isolating surface temperature row
rows_to_skip = [*range(1,18,1)]
rows_to_skip.remove(17) # rows that aren't surface temperature

ssp126_rows_to_skip = [*range(1,18,1)]
ssp126_rows_to_skip.remove(7)

temp119 = pd.read_csv('/home/jovyan/galen_course/SSP119_magicc_202408131930.csv',skiprows=rows_to_skip)
temp126 = pd.read_csv('/home/jovyan/galen_course/SSP126_magicc_202408131930.csv',skiprows=ssp126_rows_to_skip)
temp245 = pd.read_csv('/home/jovyan/galen_course/SSP245_magicc_202408131930.csv',skiprows=rows_to_skip)
temp370 = pd.read_csv('/home/jovyan/galen_course/SSP370_magicc_202408131929.csv',skiprows=rows_to_skip)
temp434 = pd.read_csv('/home/jovyan/galen_course/SSP434-over_magicc_202408131929.csv',skiprows=rows_to_skip)
temp585 = pd.read_csv('/home/jovyan/galen_course/SSP585_magicc_202408131252.csv',skiprows=rows_to_skip)

# selecting columns with years and data
years = [*range(1995,2101,1)]
temps119,temps126,temps245,temps370,temps434,temps585 = [],[],[],[],[],[]
for yr in years:
    temps119.append(temp119[str(yr)].values[0]) # temperature values in Kelvin
    temps126.append(temp126[str(yr)].values[0])
    temps245.append(temp245[str(yr)].values[0])
    temps370.append(temp370[str(yr)].values[0])
    temps434.append(temp434[str(yr)].values[0])
    temps585.append(temp585[str(yr)].values[0])

In [24]:
scenario_temps = pd.DataFrame(
    data=[temps119,temps126,temps245,temps370,temps434,temps585],
    index=['ssp119','ssp126','ssp245','ssp370','ssp434-over','ssp585'],
    columns=years)

In [25]:
scenario_temps

,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
ssp119,0.542365,0.6064,0.63513,0.6723,0.726534,0.772131,0.805662,0.827141,0.844298,0.857234,...,1.334563,1.334569,1.331135,1.323279,1.314079,1.303480,1.295357,1.285390,1.277878,1.273237
ssp126,0.542365,0.6064,0.63513,0.6723,0.726534,0.772131,0.805662,0.827141,0.844298,0.857234,...,1.699985,1.697550,1.693881,1.686661,1.677690,1.668055,1.660000,1.651845,1.646145,1.641430
ssp245,0.542365,0.6064,0.63513,0.6723,0.726534,0.772131,0.805662,0.827141,0.844298,0.857234,...,2.615342,2.630258,2.641531,2.646626,2.649441,2.650575,2.653598,2.655424,2.660787,2.667971
ssp370,0.542365,0.6064,0.63513,0.6723,0.726534,0.772131,0.805662,0.827141,0.844298,0.857234,...,3.606273,3.646933,3.688977,3.729935,3.769990,3.805186,3.840128,3.876833,3.915078,3.958813
ssp434-over,0.542365,0.6064,0.63513,0.6723,0.726534,0.772131,0.805662,0.827141,0.844298,0.857234,...,2.112831,2.118400,2.121870,2.118731,2.115295,2.110248,2.104818,2.099186,2.095461,2.093201
ssp585,0.542365,0.6064,0.63513,0.6723,0.726534,0.772131,0.805662,0.827141,0.844298,0.857234,...,4.450363,4.510660,4.568755,4.619570,4.668292,4.711446,4.755020,4.802105,4.852823,4.902124

In [26]:
scenario_temps.index.name = 'Scenario'

In [27]:
scenario_temps

,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
Scenario,,,,,,,,,,,,,,,,,,,,,
ssp119,0.542365,0.6064,0.63513,0.6723,0.726534,0.772131,0.805662,0.827141,0.844298,0.857234,...,1.334563,1.334569,1.331135,1.323279,1.314079,1.303480,1.295357,1.285390,1.277878,1.273237
ssp126,0.542365,0.6064,0.63513,0.6723,0.726534,0.772131,0.805662,0.827141,0.844298,0.857234,...,1.699985,1.697550,1.693881,1.686661,1.677690,1.668055,1.660000,1.651845,1.646145,1.641430
ssp245,0.542365,0.6064,0.63513,0.6723,0.726534,0.772131,0.805662,0.827141,0.844298,0.857234,...,2.615342,2.630258,2.641531,2.646626,2.649441,2.650575,2.653598,2.655424,2.660787,2.667971
ssp370,0.542365,0.6064,0.63513,0.6723,0.726534,0.772131,0.805662,0.827141,0.844298,0.857234,...,3.606273,3.646933,3.688977,3.729935,3.769990,3.805186,3.840128,3.876833,3.915078,3.958813
ssp434-over,0.542365,0.6064,0.63513,0.6723,0.726534,0.772131,0.805662,0.827141,0.844298,0.857234,...,2.112831,2.118400,2.121870,2.118731,2.115295,2.110248,2.104818,2.099186,2.095461,2.093201
ssp585,0.542365,0.6064,0.63513,0.6723,0.726534,0.772131,0.805662,0.827141,0.844298,0.857234,...,4.450363,4.510660,4.568755,4.619570,4.668292,4.711446,4.755020,4.802105,4.852823,4.902124

In [28]:
scenario_temps.to_csv('/home/jovyan/galen_course/scenario_temperatures.csv')

## ATMOSPHERIC C02

In [1]:
# 	variable
# 2	Atmospheric Concentrations|CO2

In [4]:
test = pd.read_csv('/home/jovyan/galen_course/SSP119_magicc_202408131930.csv')

In [6]:
test[test['variable']=='Atmospheric Concentrations|CO2']

,climate_model,data_id,model,quantile,reference_period_end_year,reference_period_start_year,region,scenario,stage,todo,...,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
15,MAGICC7,47d205a5-0b61-4699-9203-881822053f71,IMAGE,0.5,NaN,NaN,World,SSP119,climate,not_relevant,...,394.62619,393.478695,392.3443,391.103875,389.9143,388.698315,387.542435,386.39125,385.227945,384.045295

In [15]:
### getting xco2 from dataframe ###

# isolating atmospheric co2 row

temp119 = pd.read_csv('/home/jovyan/galen_course/SSP119_magicc_202408131930.csv')
ssp119_xco2 = temp119[temp119['variable']=='Atmospheric Concentrations|CO2']

temp126 = pd.read_csv('/home/jovyan/galen_course/SSP126_magicc_202408131930.csv')
ssp126_xco2 = temp126[temp126['variable']=='Atmospheric Concentrations|CO2']

temp245 = pd.read_csv('/home/jovyan/galen_course/SSP245_magicc_202408131930.csv')
ssp245_xco2 = temp245[temp245['variable']=='Atmospheric Concentrations|CO2']

temp370 = pd.read_csv('/home/jovyan/galen_course/SSP370_magicc_202408131929.csv')
ssp370_xco2 = temp370[temp370['variable']=='Atmospheric Concentrations|CO2']

temp434 = pd.read_csv('/home/jovyan/galen_course/SSP434-over_magicc_202408131929.csv')
ssp434_xco2 = temp434[temp434['variable']=='Atmospheric Concentrations|CO2']

temp585 = pd.read_csv('/home/jovyan/galen_course/SSP585_magicc_202408131252.csv')
ssp585_xco2 = temp585[temp585['variable']=='Atmospheric Concentrations|CO2']

# selecting columns with years and data
years = [*range(1995,2101,1)]
xco2_119,xco2_126,xco2_245,xco2_370,xco2_434,xco2_585 = [],[],[],[],[],[]
for yr in years:
    xco2_119.append(ssp119_xco2[str(yr)].values[0]) # temperature values in Kelvin
    xco2_126.append(ssp126_xco2[str(yr)].values[0])
    xco2_245.append(ssp245_xco2[str(yr)].values[0])
    xco2_370.append(ssp370_xco2[str(yr)].values[0])
    xco2_434.append(ssp434_xco2[str(yr)].values[0])
    xco2_585.append(ssp585_xco2[str(yr)].values[0])

In [16]:
scenario_xco2 = pd.DataFrame(
    data=[xco2_119,xco2_126,xco2_245,xco2_370,xco2_434,xco2_585],
    index=['ssp119','ssp126','ssp245','ssp370','ssp434-over','ssp585'],
    columns=years)

In [18]:
scenario_xco2.index.name = 'Scenario'

In [19]:
scenario_xco2.to_csv('/home/jovyan/galen_course/scenario_atm_co2.csv')